platform :ios, '10.0'

target 'Utils' do

use_frameworks!

pod 'SnapKit'

pod 'SwiftEntryKit' # 自定义弹框
pod 'XLActionController' #底部sheet

pod 'PagingViewKit', '~> 1.1.5'

pod 'SKPhotoBrowser'
pod 'Kingfisher', '~> 5.14.1'

pod 'URLNavigator'

#pod 'MobileVLCKit'

end
